site_name: Website of a Doctor Candidate
site_url: https://yliu-fe.github.io
site_author: yliu-fe
site_description: 我的个人网页

repo_name: yliu-fe
repo_url: https://github.com/yliu-fe/yliu-fe.github.io

nav:
  - 关于:
    - About/index.md
    - Curriculum Vitae: About/cv.md
  - 计算机笔记:
    - Techs/tech_index.md
    - Matlab笔记:
      - 引导页: Techs/Notes for Matlab/general.md
    - MkDocs疑难杂症研究:
      - 引入MathJax: Techs/Notes for Mkdocs/MathJax的引入.md
      - 如何联动Github Pages: Techs/Notes for Mkdocs/Github pages note.md
      - 如何使用PyMdown blocks: Techs/Notes for Mkdocs/PyMdown_blocks.md
      - 如何配置代码块: Techs/Notes for Mkdocs/Settings_Code_Blocks.md
      - 利用Giscus配置评论区: Techs/Notes for Mkdocs/Comment with Giscus.md
    - Astro笔记: 
      - Astro部署网页至Github Pages: Techs/Notes for Astro/Deploy Astro to Github Pages.md
    - LaTeX杂症研究:
      - 利用threeparttable包实现表格的note: Techs/Notes for LaTeX/Notes for Table.md
    - Python掉坑笔记: 
      - 基本语法:
        - 形参"args"和"kwargs": Techs/Notes for Python/Basic Syntax/args_kwargs.md
      - 各类包:
        - numpy专题: Techs/Notes for Python/Packages/numpy.md
      - CS61A:
        - 引导页：希望这不是一个笑话: Techs/Notes for Python/CS61A/61a_index.md
        - 高阶函数、递归和hw2: Techs/Notes for Python/CS61A/recursive.md 
      - Fluent Python:
        - Ch1 Python Data Model: Techs/Notes for Python/FluentPython/1 Python Data Model.md
        - Ch2 An Array of Sequences: Techs/Notes for Python/FluentPython/2 An Array of Sequences.md
  - 专业笔记:
    - Majors/Major_index.md
    - 截面数据计量经济学:
      - Majors/Cross-Sectional Econometrics/About cross-section data.md
      - 一、线性模型和最小二乘法: Majors/Cross-Sectional Econometrics/1_OLS.md
      - 二、大样本理论（渐进理论）: Majors/Cross-Sectional Econometrics/2_LargeSample.md
    - 时间序列计量经济学:
      - Majors/Time-Series Analysis/TS_index.md
      - 一、一点预备内容: Majors/Time-Series Analysis/1_Background.md
      - 二、基本时间序列模型: Majors/Time-Series Analysis/2_Basic TimeSeries.md
      - 三、条件异方差模型: Majors/Time-Series Analysis/3_Conditional Heteroscedasticity.md
    - 非参数方法:
      - 一、高斯过程: Majors/Non_Parametric/Gaussian_Process.md
    - 强化学习:
      - Majors/Reinforcement Learning/RL_index.md
      - Deepmind RL:
        - 关于课程: Majors/Reinforcement Learning/Deepmind RL/DMRL_index.md
        - 一、强化学习的介绍: Majors/Reinforcement Learning/Deepmind RL/1_Introduction.md
      - 伯克利CS188:
        - 关于课程: Majors/Reinforcement Learning/CS188/Introduction.md
        - 作业:
          - 作业1 搜索: Majors/Reinforcement Learning/CS188/homework/Homework 1 Search.md
        - 项目:
          - 项目1 搜索: Majors/Reinforcement Learning/CS188/projects/Project 1 Search.md
        - 1.1 盲目搜索: Majors/Reinforcement Learning/CS188/Section1.1 Uninformed Search.md
        - 1.2 A*搜索和启发式搜索: Majors/Reinforcement Learning/CS188/Section1.2 A_star Search and Heuristics.md
      - 伯克利CS285:
        - 关于课程: Majors/Reinforcement Learning/CS285/CS285_index.md
        - 二、模仿学习: Majors/Reinforcement Learning/CS285/2_Imitation Learning.md
        - 作业一、模仿学习: Majors/Reinforcement Learning/CS285/HW1_Imitation Learning.md
        - 四、强化学习导引: Majors/Reinforcement Learning/CS285/4_Intro of RL.md
        - 作业二、策略梯度: Majors/Reinforcement Learning/CS285/HW2_Policy_Gradients.md
  - 消遣娱乐:
    - Entertainment/ett_index.md
    - 拉丁语:
      - Entertainment/Lingua Latino/Latin_index.md
      
theme:
  name: material
  custom_dir: overrides
  language: zh
  palette: 
        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换为夜间模式
      primary: indigo
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换为日间模式
      accent: cyan

  font: 
    text: Noto Sans SC
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yliu-fe
      name: GitHub | yliu-fe

copyright: Copyright &copy; 2023 Y. Liu

plugins:
  - search:
      lang: 
        -en
        -ja
  - git-revision-date-localized:
      enable_creation_date: true
      exclude:
        - index.md
      type: date

markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js