site_name: Website of a Doctor Candidate
site_url: https://yliu-fe.github.io
site_author: yliu-fe
site_description: 我的个人网页

repo_name: yliu-fe
repo_url: https://github.com/yliu-fe/yliu-fe.github.io

nav:
  - 关于:
    - About/index.md
    - Curriculum Vitae: About/cv.md
  - 计算机笔记:
    - Techs/tech_index.md
    - MkDocs疑难杂症研究:
      - 引入MathJax: Techs/Notes for Mkdocs/MathJax的引入.md
      - 如何联动Github Pages: Techs/Notes for Mkdocs/Github pages note.md
      - 如何使用PyMdown blocks: Techs/Notes for Mkdocs/PyMdown_blocks.md
      - 如何配置代码块: Techs/Notes for Mkdocs/Settings_Code_Blocks.md
  - 专业笔记:
    - Majors/Major_index.md
    - 截面数据计量经济学:
      - Majors/Cross-Sectional Econometrics/About cross-section data.md
      - 一、线性模型和最小二乘法: Majors/Cross-Sectional Econometrics/1_OLS.md

theme:
  name: material
  language: zh
  palette: 
        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换为夜间模式
      primary: indigo
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换为日间模式
      accent: cyan

  font: 
    text: Noto Sans SC
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yliu-fe
      name: GitHub | yliu-fe

plugins:
  - search:
      lang: 
        -en
        -ja
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js